# Generated by Django 5.2.4 on 2025-07-14 03:44

import django.db.models.deletion
import veterinaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alto',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[veterinaria.validators.esMayorACero]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[veterinaria.validators.esMayorACero]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[veterinaria.validators.esMayorACero, veterinaria.validators.esMenorACien]),
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.paciente')),
            ],
        ),
    ]
